### ISSUE TITLE
How to use cookie

### ISSUE THREAD

**Issue by ijalabt1** [imankitkumar/Filpkart-auto-buy-with-captcha-bypass#1]
I generate cookies using generatecookie.py and then copied the cookie string which displayed and pasted in config file.
After that product link also placed and then i ran order.php it shows invalid/invalid cookie

**Comment by imankitkumar** [comment]
hey... after generating your cookie with the help of generate_cookie.py file. only copy the S= & SN= values ... delete everything else..
valid cookie example:

$set_cookie = 's=value;sn=value';

hope it helps :)

**Comment by ijalabt1** [comment]
Done
